@startuml

!theme reddress-lightorange

enum EventType {
    None
    MouseButtonPressed
    MouseButtonReleased
    MouseScrolled
    WindowResized
    WindowClosed
    WindowHasFocus
    WindowLostFocus
    KeyTyped
    KeyPressed
    KeyReleased
}

enum EventCategory {
    None
    Application
    Input
    Keyboard
    Mouse
    MouseButton
}

abstract class Event {
    - EventType event
    - EventCategory category
    {abstract} + EventType getEvent()
    {abstract} + EventType getCategory()
    {abstract} + String toString()
    + boolean isCategory(EventCategory category)
}

enum MouseButton {
    Left
    Right
    Middle
}

class MouseButtonEvent extends Event {
    - MouseButton button
    # MouseButtonEvent(MouseButton button)
    + MouseButton GetButton()
}

class MouseButtonPressedEvent extends MouseButtonEvent {
    + MouseButtonPressedEvent(MouseButton button)
}

class MouseButtonReleasedEvent extends MouseButtonEvent {
    + MouseButtonReleasedEvent(MouseButton button)
}

class MouseMovedEvent extends Event {
    - float x
    - float y
    + MouseMovedEvent(float x, float y)
    + float getX()
    + float getY()
}

class MouseScrolledEvent extends Event {
    - float xOffset
    - float yOffset
    + MouseScrolledEvent(float xOffset, float yOffset)
    + float getXOffset()
    + float getYOffset()
}

class KeyEvent extends Event {
    - int keycode
    # KeyEvent(int keycode)
    + int getKeycode()
}

class KeyPressedEvent extends KeyEvent {
    - int repeatCount
    + KeyKeyPressedEvent(int keycode, int repeatCount)
    + int getRepeatCount()
}

class KeyReleasedEvent extends KeyEvent {
    + KeyKeyReleasedEvent(int keycode)
}

class WindowResizedEvent extends Event {
    - int height
    - int width
    + WindowResizedEvent(int height, int width)
    + int getHeight()
    + int getWidth()
}
class WindowClosedEvent extends Event {
    + WindowClosedEvent()
}

class WindowHasFocus extends Event {
    + WindowHasFocus()
}

class WindowLostFocus extends Event {
    + WindowLostFocus()
}

EventType o-- Event
EventCategory o-- Event
MouseButton o-- MouseButtonEvent

@enduml
