@startuml

!theme reddress-lightorange
footer Layers

class LayerStack {
    - List<Layer> layers
    + LayerStack()
    + void pushLayer(Layer layer)
    + void pushOverlay(Layer overlay)
    + void popLayer(Layer layer)
    + void popOverlay(Layer overlay)
}

abstract class Layer {
    # String debugName
    + Layer()
    + Layer(String name)
    {abstract} + void OnAttach()
    {abstract} + void OnDetach()
    {abstract} + void OnUpdate(TimeStep ts)
    {abstract} + void OnEvent(Event event)
    {abstract} + boolean equals(Layer other)
}

LayerStack --o "0.. " Layer : contains

@enduml
